tiling: Remove topBarAdjustment from workArea
PaperWM-community/PaperWM pull request #9
Opened 2021-12-23 20:23 UTC by tadfisher

This removes the hardcoded top margin, which I don't believe is necessary because `getWorkAreaForMonitor` already accounts for the panel area.

This improves compatibility with bottom-pinned panels such as when using the Dash to Panel extension.

2021-12-25 18:23 UTC, smichel17 requested changes
I'll say the same thing as in <https://github.com/PaperWM-community/PaperWM/pull/13>— is this related to GNOME 40 support, or an unrelated QoL improvement or code cleanup? If the latter, I think it would be better to send the PR upstream instead.

2022-07-10 16:26 UTC, smichel17 approved these changes
Now that we're going ahead with a hard fork, this looks good to me, although I'd like to test it first. Anyone else want to help?

2022-07-10 16:42 UTC, Thesola10 requested changes

2022-07-11 18:26 UTC, tadfisher commented on tiling.js
> -var panelBox = Main.layoutManager.panelBox;
Should be fixed, thanks!

2022-08-15 11:35 UTC, smichel17 commented
Updated on top of `master` after resolving accidentally added commits in https://github.com/PaperWM-community/PaperWM/pull/22

2022-08-15 11:41 UTC, smichel17 approved these changes
Works for me (including stacking)

2022-08-15 11:44 UTC, smichel17 commented
Note: The "horizontal margin" setting is not working for me, but that was broken before this commit as well

2022-08-15 11:44 UTC, merged